"""Build convex dice meshes and verify face geometry with SymPy."""
from pathlib import Path
from itertools import combinations, product
import json
import math
import sympy as sp

phi=(1+sp.sqrt(5))/2
meshes={
    4:[[1,1,1],[-1,-1,1],[-1,1,-1],[1,-1,-1]],
    6:list(product([-1,1],repeat=3)),
    8:[[0,1,0],[0,-1,0],[1,0,0],[0,0,1],[-1,0,0],[0,0,-1]],
    12:list(product([-1,1],repeat=3))+[
        p for a,b in product([-1,1],repeat=2)
        for p in [(0,a/phi,b*phi),(a/phi,b*phi,0),(a*phi,0,b/phi)]
    ],
}
output={}
for sides,raw in meshes.items():
    exact=[sp.Matrix(v) for v in raw]
    points=[[float(c) for c in v] for v in exact]
    faces=set()
    for a,b,c in combinations(range(len(points)),3):
        ab=[points[b][j]-points[a][j] for j in range(3)]
        ac=[points[c][j]-points[a][j] for j in range(3)]
        n=[ab[1]*ac[2]-ab[2]*ac[1],ab[2]*ac[0]-ab[0]*ac[2],ab[0]*ac[1]-ab[1]*ac[0]]
        if sum(x*x for x in n)<1e-10:continue
        distances=[sum(n[j]*(p[j]-points[a][j]) for j in range(3)) for p in points]
        if min(distances)<-1e-7 and max(distances)>1e-7:continue
        faces.add(tuple(i for i,d in enumerate(distances) if abs(d)<1e-7))
    assert len(faces)==sides
    radius=sp.sqrt(exact[0].dot(exact[0]))
    ordered=[]
    for face in sorted(faces):
        center=sum((exact[i] for i in face),sp.zeros(3,1))/len(face)
        normal=center/sp.sqrt(center.dot(center))
        u=exact[face[0]]-center;u=u/sp.sqrt(u.dot(u));v=normal.cross(u)
        order=sorted(face,key=lambda i:math.atan2(float((exact[i]-center).dot(v)),float((exact[i]-center).dot(u))))
        # Exact planarity and equal-radius checks validate the generated polyhedra.
        for i in face:
            assert sp.simplify(center.dot(exact[i]-center))==0
            assert sp.simplify(exact[i].dot(exact[i])-radius**2)==0
        ordered.append(order)
    edges={tuple(sorted((f[i],f[(i+1)%len(f)]))) for f in ordered for i in range(len(f))}
    assert sp.Integer(len(raw))-len(edges)+len(faces)==2
    output[sides]={'vertices':[[round(float(c/radius),9) for c in v] for v in exact],'faces':ordered}
    print(f'D{sides}: {len(raw)} vertices, {len(edges)} edges, {len(faces)} planar faces; SymPy verified')
target=Path(__file__).resolve().parents[2]/'lite-dice-geometry.js'
target.write_text('/* Generated by assets/dice/build-geometry.py; unit-radius convex polyhedra. */\nglobalThis.LITE_DICE_GEOMETRY='+json.dumps(output,separators=(',',':'))+';\n',encoding='utf-8')
